CREATE DATABASE [Cars]
GO
USE [Cars]
GO
CREATE TABLE [Mark](
[MarkID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(30) NOT NULL
);
CREATE TABLE [Model](
[ModelID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(30) NOT NULL,
[Year] NVARCHAR(9) NOT NULL,
[MarkID] INT FOREIGN KEY REFERENCES[Mark](MarkID) NOT NULL,
);
CREATE TABLE [Country](
[CountryID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(100) NOT NULL
);
CREATE TABLE[State](
[StateID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(100) NOT NULL,
[CountryId] INT FOREIGN KEY REFERENCES[Country](CountryId) NOT NULL
);
CREATE TABLE[Locality](
[LocalityID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(40) NOT NULL,
[StateId] INT FOREIGN KEY REFERENCES[State](StateId) NOT NULL
);

CREATE TABLE[Adress](
[AdressID] INT PRIMARY KEY IDENTITY,
[Street] NVARCHAR(100)  NOT NULL,
[NumberOfHome] NVARCHAR(10)  NOT NULL,
[NumberOfApartments] NVARCHAR(4)  NOT NULL,
[LocalityId] INT FOREIGN KEY REFERENCES[Locality](LocalityId) NOT NULL,
[PostCode] NVARCHAR(15) NOT NULL
);
CREATE TABLE [Owner](
[OwnerID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL,
[MiddleName] NVARCHAR(50),
[LastName] NVARCHAR(50) NOT NULL,
[AdressID] INT FOREIGN KEY REFERENCES[Adress](AdressID) NOT NULL,
);
CREATE TABLE [Car](
[CarID] INT PRIMARY KEY IDENTITY,
[Number] NVARCHAR(6) NOT NULL,
[Region] INT NOT NULL,
[InsuranceNumber] NVARCHAR(50) NOT NULL,
[Color] NVARCHAR(30) NOT NULL,
[Year] NVARCHAR(4) NOT NULL,
[OwnerID] INT FOREIGN KEY REFERENCES[Owner](OwnerID) NOT NULL,
[ModelID] INT FOREIGN KEY REFERENCES[Model](ModelID) NOT NULL
);
