USE [master]
GO
CREATE DATABASE [Cars]
GO
USE [Cars]
GO
CREATE TABLE [Mark](
[MarkID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(30) NOT NULL
);
CREATE TABLE [Series](
[SeriesID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(30) NOT NULL,
[MarkID] INT FOREIGN KEY REFERENCES[Mark](MarkID) NOT NULL
);
CREATE TABLE [Model](
[ModelID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(30) NOT NULL,
[Year] INT NOT NULL,
[SeriesID] INT FOREIGN KEY REFERENCES[Series](SeriesID) NOT NULL,
);
CREATE TABLE [Country](
[CountryID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(100) NOT NULL
);
CREATE TABLE[State](
[StateID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(100) NOT NULL
);
CREATE TABLE[Locality](
[LocalityID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(40) NOT NULL
);

CREATE TABLE[Adress](
[AdressID] INT PRIMARY KEY IDENTITY,
[Address1] NVARCHAR(100)  NOT NULL,
[Address2] NVARCHAR(100),
[CountryId] INT FOREIGN KEY REFERENCES[Country](CountryId) NOT NULL,
[StateId] INT FOREIGN KEY REFERENCES[State](StateId) NOT NULL,
[LocalityId] INT FOREIGN KEY REFERENCES[Locality](LocalityId) NOT NULL,
[PostCode] NVARCHAR(15) NOT NULL
);
CREATE TABLE [Owner](
[OwnerID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(20) NOT NULL,
[MiddleName] NVARCHAR(20),
[LastName] NVARCHAR(20) NOT NULL,
[AdressID] INT FOREIGN KEY REFERENCES[Adress](AdressID) NOT NULL,
);
CREATE TABLE [Car](
[CarID] INT PRIMARY KEY IDENTITY,
[Number] NVARCHAR(6) NOT NULL,
[Region] INT NOT NULL,
[OwnerID] INT FOREIGN KEY REFERENCES[Owner](OwnerID) NOT NULL,
[InsuranceNumber] NVARCHAR(50),
[ModelID] INT FOREIGN KEY REFERENCES[Model](ModelID) NOT NULL,
[Color] NVARCHAR(30) NOT NULL
);
GO
CREATE DATABASE [Users]
GO
USE [Users]
GO
CREATE TABLE[Role](
[RoleID] INT PRIMARY KEY IDENTITY,

);