CREATE DATABASE [Users]
GO
USE [Users]
GO
CREATE TABLE[Role](
[RoleID] INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(50) NOT NULL
);
GO
CREATE TABLE[User](
[UserID] INT PRIMARY KEY IDENTITY,
[Login] NVARCHAR(320) NOT NULL,
[Password] NVARCHAR(320) NOT NULL,
[FirstName] NVARCHAR(320) NOT NULL,
[MidleName] NVARCHAR(320),
[LastName] NVARCHAR(320) NOT NULL,
[Email] NVARCHAR(320) NOT NULL,
[NumberPhone]NVARCHAR(11) NOT NULL,
[RoleID] INT FOREIGN KEY REFERENCES[Role](RoleID)
);