//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarID { get; set; }
        public string Number { get; set; }
        public int Region { get; set; }
        public int OwnerID { get; set; }
        public string InsuranceNumber { get; set; }
        public int ModelID { get; set; }
        public string Color { get; set; }
        public string Year { get; set; }
    
        public virtual Model Model { get; set; }
        public virtual Owner Owner { get; set; }
    }
}
