//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationCarApp.Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int CarID { get; set; }
        public string Number { get; set; }
        public string Region { get; set; }
        public string VIN { get; set; }
        public string InsuranceNumber { get; set; }
        public Nullable<int> ColorID { get; set; }
        public string Year { get; set; }
        public int OwnerID { get; set; }
        public int ModelID { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Model Model { get; set; }
        public virtual Person Person { get; set; }
    }
}
